microscope:
  name: 'Ocus40'
  type: 'WholeSlideScanner'
  vendor: 'Grundium'
macro:
  pixel_size_um: 81.0  # Default macro pixel size
  requires_cropping: true
  slide_bounds:
    x_min: 0
    x_max: 938
    y_min: 19
    y_max: 331
  description: 'Ocus40 whole slide scanner with slide holder visible in macro image'
