
microscope:
  name: 'PPM'
  type: 'UprightBrightfield'
  camera: 'LOCI_CAMERA_003' # JAI AP-3200T-USB

stage:
  r_stage: 'KBD101_Thor_Rotation' 
  z_stage: 'ZStage'
  x_limit: 
    low: -17000.0 
    high: 33000.0
  y_limit: 
    low: -12000.0  
    high: 13000.0
  z_limit: 
    low: -1800 # 40x will hit at 850-900
    high: 100
  id: 'LOCI_Stage_002' # Prior stage

imaging_mode:
  LOCI_CAMERA_002:
    ppm_10x:
      objective_lens: 'LOCI_10x_001'
      pixel_size_um: 0.4537
    ppm_20x:
      objective_lens: 'LOCI_20x_003'
      pixel_size_um: 0.2271
    ppm_40x:
      objective_lens: 'LOCI_40x_001'    
      pixel_size_um: 0.1142
  LOCI_CAMERA_003:
    ppm_10x:
      objective_lens: 'LOCI_10x_001'
      pixel_size_um: 0.6866
    ppm_20x:
      objective_lens: 'LOCI_20x_003'
      pixel_size_um: 0.3433
    ppm_40x:
      objective_lens: 'LOCI_40x_001'    
      pixel_size_um: 0.1709

white_balance:    
  ppm:
    crossed: [1.33363137 1.17596971 1.0]   # +0
    uncrossed: [1.97220307 2.38955037 1.0  ] # +90
    positive: [1.38673833 1.6424885  1.0]  # +5
    negative: [1.81489925 1.70723008 1.0] # -5
  default:
    default: [1.000, 1.000, 1.000]

slide_size:
  x: 40000
  y: 20000
  
autofocus:
  n_steps: 9 # minimum 3
  search_range: 20
  n_tiles: 5
  #interp_strength: 100

background_correction:
  enabled: true
  method: "divide"
  background_folder: "D:/2025QPSC/data/background_tiles"
