# ========== PPM MICROSCOPE CONFIGURATION ==========
# References hardware from resources_LOCI.yml

# ========== REUSABLE DEFINITIONS ==========

# Camera-specific exposure and gain settings
# For JAI camera exposures:
#   - 'all': Single exposure value for R,G,B channels (simplified white balance via gains only)
#   - 'r,g,b': Individual channel exposures (advanced white balance via exposure ratios)
#   - ConfigManager should check for 'all' first, fallback to r,g,b if not present
#   - Gains are always applied per-channel regardless of exposure mode
camera_settings:
  LOCI_CAMERA_002:  # MicroPublisher 6
    ppm_exposures: &cam002_ppm_exposures
      negative_ms: 500
      crossed_ms: 800
      positive_ms: 500
      uncrossed_ms: 10
    ppm_gains: &cam002_ppm_gains  # Constant across all angles
      r: 1.2
      g: 1.0
      b: 1.1


  LOCI_CAMERA_003:  # JAI prism camera (supports both single and RGB exposure modes)
  #need to be individual for each objective!!!
    ppm_exposures: &cam003_ppm_exposures
      negative:
        all_ms: 500  # Single exposure for all channels (simplified mode)
        r_ms: 450    # Individual RGB exposures (advanced mode)
        g_ms: 500    # ConfigManager chooses which mode to use
        b_ms: 550
      crossed:
        all_ms: 800  
        r_ms: 750    
        g_ms: 800
        b_ms: 850
      positive:
        all_ms: 500  
        r_ms: 450    
        g_ms: 500
        b_ms: 550
      uncrossed:
        all_ms: 10   
        r_ms: 8      
        g_ms: 10
        b_ms: 12
    ppm_gains: &cam003_ppm_gains  # Always applied per-channel for white balance
      negative: {r: 1.0, g: 1.0, b: 1.0}
      crossed: {r: 1.1, g: 1.0, b: 1.05}
      positive: {r: 1.0, g: 1.0, b: 1.0}
      uncrossed: {r: 1.2, g: 1.0, b: 1.1}


# ========== MICROSCOPE CONFIGURATION ==========

microscope:
  name: 'PPM'
  type: 'UprightBrightfield'
  detector_in_use: null
  objective_in_use: null
  modality: null

# ========== MODALITY-SPECIFIC SETTINGS ==========
# Only inherent properties of the imaging modality

modalities:
  ppm:
    # Rotation stage is separate hardware, not part of XYZ stage
    rotation_stage:
      device: 'KBD101_Thor_Rotation'
      type: 'polarizer' # vs sample
    rotation_angles:  #ticks are double angles due to how the PPM was made, so 90 ticks is a 180 degree rotation
      - name: 'negative'
        tick: -5
      - name: 'crossed'
        tick: 0
      - name: 'positive'
        tick: 5
      - name: 'uncrossed'
        tick: 90
    background_correction:
      enabled: true
      method: 'divide'
      base_folder: "D:/2025QPSC/data/background_tiles"
      # Path: {base_folder}/{microscope}/ppm/{magnification}x/{detector}/{angle_name}_background.tif
        
  brightfield:
    background_correction:
      enabled: true
      method: 'divide'
      base_folder: "D:/2025QPSC/data/background_tiles"
      # Path: {base_folder}/{microscope}/brightfield/{magnification}x/{detector}/background.tif

# ========== DETECTOR CAPABILITIES ==========
# Hardware capabilities only

detectors:
  LOCI_CAMERA_002:  # MicroPublisher 6
    compatible_modalities: ['ppm', 'brightfield']
    channel_control: 'gain_only'  # Can adjust R,G,B gains but single exposure
    short_name: 'mp6'
    
  LOCI_CAMERA_003:  # JAI prism camera  
    compatible_modalities: ['ppm', 'brightfield']
    channel_control: 'full_rgb'  # Can adjust R,G,B exposures and gains independently
    short_name: 'jai'

# ========== OBJECTIVE-SPECIFIC SETTINGS ==========
# Lens-specific properties with integrated autofocus parameters

objectives:
  LOCI_10x_001:
    autofocus:
      n_steps: 9
      search_range_um: 50
      n_tiles: 5
    pixel_size_xy_um:
      LOCI_CAMERA_002: 0.4537
      LOCI_CAMERA_003: 0.6866
      
  LOCI_20x_003:
    autofocus:
      n_steps: 11
      search_range_um: 25
      n_tiles: 5
    pixel_size_xy_um:
      LOCI_CAMERA_002: 0.2271
      LOCI_CAMERA_003: 0.3433
      
  LOCI_40x_001:
    autofocus:
      n_steps: 15
      search_range_um: 10
      n_tiles: 7
    pixel_size_xy_um:
      LOCI_CAMERA_002: 0.1142
      LOCI_CAMERA_003: 0.1709

# ========== ACQUISITION PROFILES ==========
# ALL combinations of modality × objective × detector
# Naming: {modality}_{magnification}x_{camera_short_name}

acquisition_profiles:
  # ===== PPM MODALITY - 10x OBJECTIVE =====
  ppm_10x_jai:
    modality: 'ppm'
    objective: 'LOCI_10x_001'
    detector: 'LOCI_CAMERA_003'
    acquisition_settings:
      exposures_ms: *cam003_ppm_exposures
      gains_rgb: *cam003_ppm_gains
      
  ppm_10x_mp6:
    modality: 'ppm'
    objective: 'LOCI_10x_001'
    detector: 'LOCI_CAMERA_002'
    acquisition_settings:
      exposures_ms: *cam002_ppm_exposures
      gains_rgb: *cam002_ppm_gains

  # ===== PPM MODALITY - 20x OBJECTIVE =====
  ppm_20x_jai:
    modality: 'ppm'
    objective: 'LOCI_20x_003'
    detector: 'LOCI_CAMERA_003'
    acquisition_settings:
      exposures_ms: *cam003_ppm_exposures
      gains_rgb: *cam003_ppm_gains
      
  ppm_20x_mp6:  # NEW - Added for completeness
    modality: 'ppm'
    objective: 'LOCI_20x_003'
    detector: 'LOCI_CAMERA_002'
    acquisition_settings:
      exposures_ms: *cam002_ppm_exposures
      gains_rgb: *cam002_ppm_gains

  # ===== PPM MODALITY - 40x OBJECTIVE =====
  ppm_40x_jai:
    modality: 'ppm'
    objective: 'LOCI_40x_001'
    detector: 'LOCI_CAMERA_003'
    acquisition_settings:
      exposures_ms: *cam003_ppm_exposures
      gains_rgb: *cam003_ppm_gains
      
  ppm_40x_mp6:  # NEW - Added for completeness
    modality: 'ppm'
    objective: 'LOCI_40x_001'
    detector: 'LOCI_CAMERA_002'
    acquisition_settings:
      exposures_ms: *cam002_ppm_exposures
      gains_rgb: *cam002_ppm_gains

  # ===== BRIGHTFIELD MODALITY - 10x OBJECTIVE =====
  bf_10x_jai:
    modality: 'brightfield'
    objective: 'LOCI_10x_001'
    detector: 'LOCI_CAMERA_003'
    acquisition_settings:
      exposure_ms: 50  
      gain: 1.0
      
  bf_10x_mp6:
    modality: 'brightfield'
    objective: 'LOCI_10x_001'
    detector: 'LOCI_CAMERA_002'
    acquisition_settings:
      exposure_ms: 50  
      gains_rgb: *cam002_ppm_gains  # Same RGB gains as PPM mode

  # ===== BRIGHTFIELD MODALITY - 20x OBJECTIVE =====
  bf_20x_jai:
    modality: 'brightfield'
    objective: 'LOCI_20x_003'
    detector: 'LOCI_CAMERA_003'
    acquisition_settings:
      exposure_ms: 80 
      gain: 1.0
      
  bf_20x_mp6:  # NEW - Added for completeness
    modality: 'brightfield'
    objective: 'LOCI_20x_003'
    detector: 'LOCI_CAMERA_002'
    acquisition_settings:
      exposure_ms: 80  
      gains_rgb: *cam002_ppm_gains

  # ===== BRIGHTFIELD MODALITY - 40x OBJECTIVE =====
  bf_40x_jai:
    modality: 'brightfield'
    objective: 'LOCI_40x_001'
    detector: 'LOCI_CAMERA_003'
    acquisition_settings:
      exposure_ms: 120  
      gain: 1.0
      
  bf_40x_mp6:  # NEW - Added for completeness
    modality: 'brightfield'
    objective: 'LOCI_40x_001'
    detector: 'LOCI_CAMERA_002'
    acquisition_settings:
      exposure_ms: 120 
      gains_rgb: *cam002_ppm_gains

# ========== STAGE CONFIGURATION ==========
# Only references XYZ stage for sample positioning

stage:
  stage_id: 'LOCI_STAGE_002'  # References Prior XYZ stage in resources
  # Note: rotation stage is referenced in modality, not here
  limits:
    x_um:
      low: -17000
      high: 33000
    y_um:
      low: -12000
      high: 13000
    z_um:
      low: -1800
      high: 100

# ========== GENERAL SETTINGS ==========

slide_size_um:
  x: 40000
  y: 20000