
microscope:
  name: 'CAMM'
  type: 'Multimodal'
lamp:
  - LED-Dev1ao0
  - Voltage

objective_slider:
  - Turret:O:35
  - Label

slide_size:
  width: 40000
  height: 20000
  # (70000, -20000)
  
stage:
  z_stage: 'ZStage:Z:32'
  f_stage: 'ZStage:F:32'
  x_limit:
    low: 0
    high: 40000
  y_limit:
    low: 0
    high: 30000
  z_limit:
    low: -10700
    high: 100
  f_limit:
    low: -18000
    high: 0
  vendor: 'ASI'
  id: 'LOCI_Stage_001'

imaging_mode:

  bf_4x:
    name: '4X Brightfield'
    description: 'LSM Imaging with 20x lens'
    is_lsm: false
    pixel_size_um: 1.105
    pixel_offset:
      x: 0
      y: 0
    z: -9.2
    f: -3200
    objective_position_label: 'Position-2'
    lamp_intensity_v: 4
    objective_lens: 'LOCI_4x_001'
    detector: 'LOCI_CAMERA_001'


  bf_20x:
    name: '20X Brightfield'
    description: 'LSM Imaging with 20x lens'
    is_lsm: false
    pixel_size_um: 0.222
    z: -10502
    f: -13350
    pixel_offset:
      x: -600
      y: 10
    objective_position_label: 'Position-1'
    lamp_intensity_v: 5
    objective_lens: 'LOCI_20x_001'
    detector: 'LOCI_CAMERA_001'
    
    
  mpm_20x:
    name: '20X LSM MP'
    description: 'LSM Imaging with 20x lens'
    is_lsm: true    
    pixel_size_um: null
    pixel_offset:
      x: -580
      y: -280
    z: -10502
    f: -13350 
    objective_position_label: 'Position-1'
    lamp_intensity_v: 5
    objective_lens: 'LOCI_20x_001'
    detector: 'LOCI_PMT_001'
     
white_balance:    
  bf:
    binLi_4x_Jul2021: [1.079, 1.0, 10.056]
    binLi_20x_May2022: [1.000, 1.011, 1.245]
    jenu_20x_Mar2024: [1.089, 1.000, 1.241]